#!/bin/sh

uci delete ucitrack.@pod_minidlna[-1] >/dev/null 2>&1
uci add ucitrack pod_minidlna >/dev/null 2>&1
uci set ucitrack.@pod_minidlna[-1].init=pod_minidlna >/dev/null 2>&1
uci commit ucitrack >/dev/null 2>&1